modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="rd"
version="0.1.2"
displayName="Minecraft: Rubylands"
displayURL="https://modrinth.com/mod/minecraft-rubylands"
logoFile="logo.png"
credits="Based on Minecraft Alpha 1.0.16 Versions, made with MCreator."
authors="StellarXRaven17"
description="A fresh coat of paint on the block game you know and love."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.rd]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.rd]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.rd]]
    modId="polytone"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rd]]
    modId="moderner_beta"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration